### ISSUE TITLE
A mistake in documentation

### ISSUE THREAD

**Issue by JacksonGL** [SRA-SiliconValley/jalangi#88]
Hi, 

There is an inconsistency issue in ```analysis2.md```:
```
// In the following callbacks one can choose to not return anything.
// If all of the callbacks return nothing, we get a passive analysis where the
// concrete execution happens unmodified and callbacks are used to observe the execution.
```
But for ```instrumentCode```, ```code``` must be returned:
```javascript
this.instrumentCodePre = function (iid, code){return code;};
```
```InstrumentCodePre``` is used in ```esnstrument.js```:
```
if (iid && sandbox.analysis && sandbox.analysis.instrumentCodePre) {
     code = sandbox.analysis.instrumentCodePre(iid, code);
}
```
This inconsistency leads to a subtle bug when I ignore the return statement.

**Comment by msridhar** [comment]
I think I fixed this one, by checking the result of `instrumentCodePre`.  Let me know if you still have a problem.
