### ISSUE TITLE
How can i use Jalangi framework in my use case

### ISSUE THREAD

**Issue by waqas-tio** [SRA-SiliconValley/jalangi#91]
Hello Sir,

I am student of Master degree and need your help regarding your Jalangi Framework.

My use case is i would like to avail Jalangi API in my chrome extension.
How is it possible to use this frame work in Chrome extension so that i can use Jalangi API functionality to analyse and debug the code bieng executed in currently by browser.

Basically i would like to create chrome dev tool extension where i would like to debug some 3rd party JS libraries. But for that i really need the hooks functionality provided by Jalangi framework.

I shall be very thankfull to you if you can guide me.

Best Regards
Waqas Abbas

**Comment by msridhar** [comment]
This version of Jalangi is unmaintained.  Please try out [Jalangi 2](https://github.com/Samsung/jalangi2).
