### ISSUE TITLE
non-minified version of demo.js

### ISSUE THREAD

**Issue by MrP-git** [SRA-SiliconValley/jalangi#92]
Is it possible to have non-minified version of demo.js used in the [demo](http://people.eecs.berkeley.edu/~gongliang13/jalangi_ff/demo_integrated.htm) website?

**Comment by msridhar** [comment]
@JacksonGL ^

**Comment by JacksonGL** [comment]
The source code of all those demos are non-minified (in the right-bottom code editor of the [demo](http://people.eecs.berkeley.edu/~gongliang13/jalangi_ff/demo_integrated.htm) page). The Jalangi framework is open-sourced in this repo and the [Jalangi2](https://github.com/Samsung/jalangi2) repo.
